# permissions for end users to edit ephemeralnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeralnamespace-editor-role
rules:
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - ephemeralnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - ephemeralnamespaces/status
  verbs:
  - get
