# permissions for end users to view ephemeralnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeralnamespace-viewer-role
rules:
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - ephemeralnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - ephemeralnamespaces/status
  verbs:
  - get
