---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - ephemeralnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - ephemeralnamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - ephemeralnamespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - namespaces/finalizers
  verbs:
  - update
- apiGroups:
  - v1.change-previewer.github.io
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
